apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-web-app
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          image: my-scalable-app:v4
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: STUDENT_NAME
              value: "Riya"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
